# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='order',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x05order\"\x99\x01\n\x0cOrderRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\t\x12\x38\n\x0brequest_arg\x18\x03 \x03(\x0b\x32#.order.OrderRequest.RequestArgEntry\x1a\x31\n\x0fRequestArgEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x0cJSONResponse\x12\x12\n\nrst_string\x18\x01 \x01(\t2J\n\x0cOrderHandler\x12:\n\x0c\x63reate_order\x12\x13.order.OrderRequest\x1a\x13.order.JSONResponse\"\x00\x62\x06proto3')
)




_ORDERREQUEST_REQUESTARGENTRY = _descriptor.Descriptor(
  name='RequestArgEntry',
  full_name='order.OrderRequest.RequestArgEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='order.OrderRequest.RequestArgEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='order.OrderRequest.RequestArgEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=175,
)

_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='order.OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='order.OrderRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='order.OrderRequest.price', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_arg', full_name='order.OrderRequest.request_arg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ORDERREQUEST_REQUESTARGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=175,
)


_JSONRESPONSE = _descriptor.Descriptor(
  name='JSONResponse',
  full_name='order.JSONResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rst_string', full_name='order.JSONResponse.rst_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=211,
)

_ORDERREQUEST_REQUESTARGENTRY.containing_type = _ORDERREQUEST
_ORDERREQUEST.fields_by_name['request_arg'].message_type = _ORDERREQUEST_REQUESTARGENTRY
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['JSONResponse'] = _JSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), dict(

  RequestArgEntry = _reflection.GeneratedProtocolMessageType('RequestArgEntry', (_message.Message,), dict(
    DESCRIPTOR = _ORDERREQUEST_REQUESTARGENTRY,
    __module__ = 'test_pb2'
    # @@protoc_insertion_point(class_scope:order.OrderRequest.RequestArgEntry)
    ))
  ,
  DESCRIPTOR = _ORDERREQUEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:order.OrderRequest)
  ))
_sym_db.RegisterMessage(OrderRequest)
_sym_db.RegisterMessage(OrderRequest.RequestArgEntry)

JSONResponse = _reflection.GeneratedProtocolMessageType('JSONResponse', (_message.Message,), dict(
  DESCRIPTOR = _JSONRESPONSE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:order.JSONResponse)
  ))
_sym_db.RegisterMessage(JSONResponse)


_ORDERREQUEST_REQUESTARGENTRY._options = None

_ORDERHANDLER = _descriptor.ServiceDescriptor(
  name='OrderHandler',
  full_name='order.OrderHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=213,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_order',
    full_name='order.OrderHandler.create_order',
    index=0,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERHANDLER)

DESCRIPTOR.services_by_name['OrderHandler'] = _ORDERHANDLER

# @@protoc_insertion_point(module_scope)
