# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_pb2 as test__pb2


class OrderHandlerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create_order = channel.unary_unary(
        '/order.OrderHandler/create_order',
        request_serializer=test__pb2.OrderRequest.SerializeToString,
        response_deserializer=test__pb2.JSONResponse.FromString,
        )


class OrderHandlerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def create_order(self, request, context):
    """format a list of events.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderHandlerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create_order': grpc.unary_unary_rpc_method_handler(
          servicer.create_order,
          request_deserializer=test__pb2.OrderRequest.FromString,
          response_serializer=test__pb2.JSONResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'order.OrderHandler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
